name: MLOps End-to-End Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: âœ… Checkout Code
      uses: actions/checkout@v3

    - name: ğŸ Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: ğŸ“¦ Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ğŸ§¹ Preprocess Data
      run: python src/preprocessing/process.py

    - name: ğŸ¤– Train Model
      run: python src/training/train.py

    - name: ğŸ“Š Evaluate Model
      run: python src/evaluation/evaluate.py

    - name: ğŸ³ Build Docker Image
      run: docker build -t churn-api .

    - name: âœ… Test Docker Container
      run: |
        docker run -d -p 8000:8000 --name churn-test churn-api
        sleep 5
        curl --fail http://localhost:8000 || (docker logs churn-test && exit 1)



    # Deployment stage (to be added later)
    # - name: ğŸš€ Deploy Model
    #   run: python src/deployment/deploy.py

    # Monitoring stage (to be added later)
    # - name: ğŸ” Monitor Model
    #   run: python src/deployment/monitor.py
